SELECT YEAR(B.SALES_DATE) YEAR, 
       MONTH(B.SALES_DATE) MONTH, 
       COUNT(DISTINCT(B.USER_ID)) PURCHASED_USERS, 
       ROUND(COUNT(DISTINCT(B.USER_ID))/C.CNT, 1) PUCHASED_RATIO
  FROM USER_INFO A, ONLINE_SALE B, (SELECT COUNT(*) CNT
                                      FROM USER_INFO 
                                     WHERE YEAR(JOINED) = 2021) C
 WHERE 1=1
   AND A.USER_ID = B.USER_ID
   AND YEAR(A.JOINED) = 2021
GROUP BY YEAR(B.SALES_DATE) , MONTH(B.SALES_DATE)
ORDER BY YEAR(B.SALES_DATE) , MONTH(B.SALES_DATE)
;