WITH RECURSIVE CTE
AS (
    SELECT 0 AS HOUR
    
    UNION ALL
    
    SELECT HOUR + 1
    FROM CTE
    WHERE HOUR < 23
)
SELECT C.HOUR, COUNT(A.ANIMAL_ID) AS COUNT
FROM CTE C 
    LEFT JOIN (
        SELECT ANIMAL_ID,
               HOUR(DATETIME) AS HOUR
        FROM ANIMAL_OUTS
    ) A
    ON C.HOUR = A.HOUR
GROUP BY C.HOUR
ORDER BY C. HOUR