SELECT DISTINCT A.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR A LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B ON A.CAR_ID = B.CAR_ID
WHERE CAR_TYPE = "세단" and START_DATE between '2022-10-01' and '2022-10-31'
GROUP BY A.CAR_ID
ORDER BY A.CAR_ID DESC